server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8090
  connection-timeout: 15000ms
  servlet:
    context-path: /common

spring:
  profiles:
    active: dev
  application:
    name: joint-common
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

dubbo:
  scan:
    basePackages: com.joint
  ## ApplicationConfig Bean
  application:
    id: id-joint-common-app
    name: joint-common
    qos:
      port: 22223
      enable: true
  ## ProtocolConfig - Bean Dubbo 服务协议配置
  protocol:
    id: id-joint-common-protocol
    name: dubbo
    # host: 192.168.8.43 - 服务IP地址(多网卡时使用)
    port: 20893
    status: server
    serialization: kryo
  ## RegistryConfig Bean
  registry:
    id: id-joint-common-registry
    address: zookeeper://localhost:2181
  ## ProviderConfig Bean
  provider:
    id: id-joint-common-provider
    version: yifan
    timeout: 30000