spring:
  rabbitmq:
    host: 192.168.8.169
    port: 5672
    username: admin
    password: admin
    virtual-host: /yifan
    cache:
      channel:
        size: 50
    # 开启ACK
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    # exchange到queue成功是否回调
    template:
      mandatory: true